# Generated by Django 4.0.3 on 2022-03-20 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number. Up to 15 digits allowed.', regex='^\\d{9,15}$')])),
                ('self_invite_code', models.CharField(blank=True, max_length=8)),
                ('activated_invite_code', models.CharField(blank=True, max_length=8)),
                ('authorization_code', models.IntegerField(max_length=6)),
                ('activation_status', models.BooleanField(default=False)),
            ],
        ),
    ]
